Product.create!(
  product_id: 2,
  name: "dummy2",
  description: "dummy2",
  price: 4000,
  category_id: 2,
  recommended_flag: true,
  carriage_flag: true,
  notdisplay_flag: false,
  image_url: "",
  image_url2: "",
  image_url3: "",
  image_url4: "",
  image_url5: "",
  image_url6: "",
  image_url7: "",
  image_url8: "",
  image_url9: "",
  image_url10: "",
  detailed_explanation: "この商品について 原材料:水(鉱水) 商品サイズ(高さx奥行x幅):23cm×29cm×43.5cm 南フランスの豊かな自然の恵みが生んだ炭酸入り天然水のペリエは、カルシウムなどのミネラルをたっぷり含んだカロリーゼロの飲み物です。 心地よい炭酸の刺激と心地よい爽快感でお食事はもちろん、リフレッシュタイムにも適切です。 お食事時のお供に、ウイスキーやジン、ワインと割ってお好みのカクテルに、お仕事や勉強、スポーツ後のリフレッシュに適切です。",
  product_spec: "ブランド ‎Perrier(ペリエ) 梱包サイズ ‎43.5 x 29 x 23 cm; 13.1 kg メーカー ‎Nestle Waters(ネスレウォーターズ) 原産国名 ‎フランス 原材料 ‎水（鉱水） 商品の重量 ‎13.1 kg",
  review_comments: "村上隆は過大評価だと思いますが、ポップでカラフルなペリエもたまにはいいかなと。キティちゃんでも同じ感覚で買いましたね。 図柄は２種類。思ったより地味で緑地に負けてる感じ。半透明なせいか。缶の方がくっきり映えるかな。 6本パックのシュリンクにもプリント有り。次はもっとポップで派手に弾けたキティちゃんでよろしく。 （限定品＋予定より早く届いたのもあるのか、ありがちな炭酸抜けはありませんでした。フレッシュで強めの炭酸。その点予約注文して良かったです） カイカイキキちゃんボトルは２４本中８本ありましたよ。 ２０２１年６月に購入して、２日後には受け取りました。1本あたり90円。アマゾン取扱い開始が２０２０年９月だったので品質が心配でしたが、１本飲んで、炭酸も抜けてないようですし、破損もありませんでした。安心しました。 賞味期限は２０２２年２月でしたよ。近所のスーパーで売っているペットボトル飲料(普通のペリエ)と同じくらいでしたよ。もちろんスーパーで、このペリエは売っていませんでした。 お世話になっているヒトたちに、プレゼントするために買いました。フラワー柄ボトルを渡しましたが、認知度は、10％ぐらいでしたよ。みんな、「かわいいね～」といって、喜んで受け取ってくれました。よかったです。 わたしは、カイカイキキちゃんボトルをキッチンに飾って、大事に少しずつ飲んでます。 味が云々より村上隆さんのデザインがよくて購入しました。とても可愛いです。人にプレゼントしても喜んで頂けるし持ち歩いていてもオシャレで気に入ってます。味も飲みやすい炭酸水です。",
  review_quantity: 500,
  rating_score: 4.6,
  brand: "",
  price_with_tax: "",
  product_demension: "",
  item_weight: "",
  order_url: "",
  asin: "",
  item_model_number: "",
  stock_out_flag: false
)

Product.create!(
  product_id: 3,
  name: "dummy3",
  description: "dummy3",
  price: 600,
  category_id: 3,
  recommended_flag: true,
  carriage_flag: true,
  notdisplay_flag: false,
  image_url: "",
  image_url2: "",
  image_url3: "",
  image_url4: "",
  image_url5: "",
  image_url6: "",
  image_url7: "",
  image_url8: "",
  image_url9: "",
  image_url10: "",
  detailed_explanation: "",
  product_spec: "",
  review_comments: "",
  review_quantity: "",
  rating_score: "",
  brand: "",
  price_with_tax: "",
  product_demension: "",
  item_weight: "",
  order_url: "",
  asin: "",
  item_model_number: "",
  stock_out_flag: true
)